const DB_KEY='gradebook_v1'
let state={subjects:[],grades:[]}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function load(){try{const s=localStorage.getItem(DB_KEY);if(s){state=JSON.parse(s)}}catch(e){}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(state))}
function el(id){return document.getElementById(id)}
function renderSubjects(){const ul=el('subjectsList');ul.innerHTML='';state.subjects.forEach(s=>{const li=document.createElement('li');li.innerHTML=`<div style="display:flex;gap:8px;align-items:center"><span style="width:12px;height:12px;border-radius:4px;background:${s.color};display:inline-block"></span><strong>${s.name}</strong></div><div><button data-id="${s.id}" class="del-sub">Изтрии</button></div>`;ul.appendChild(li)});populateSubjectSelect()}
function populateSubjectSelect(){const sel=el('selSubject');sel.innerHTML='';state.subjects.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;sel.appendChild(o)})}
function renderGrades(){const tbody=document.querySelector('#gradesTable tbody');tbody.innerHTML='';state.grades.sort((a,b)=>b.date.localeCompare(a.date)).forEach(g=>{const subj=state.subjects.find(s=>s.id===g.subject) || {name:'-'};const tr=document.createElement('tr');tr.innerHTML=`<td>${subj.name}</td><td>${g.value}</td><td>${g.date}</td><td>${g.type}</td><td>${g.comment||''}</td><td><button data-id="${g.id}" class="del-grade">Изтрии</button></td>`;tbody.appendChild(tr)})}
function computeStats(){const stats=el('stats');stats.innerHTML='';const map={};state.subjects.forEach(s=>map[s.id]={name:s.name,total:0,count:0});state.grades.forEach(g=>{const m=map[g.subject];if(m){m.total+=Number(g.value);m.count+=1}});const overall={total:0,count:0};Object.values(map).forEach(m=>{if(m.count){const avg=+(m.total/m.count).toFixed(2);const div=document.createElement('div');div.className='stat';div.innerHTML=`<div><strong>${m.name}</strong></div><div>Среден успех: ${avg}</div><div>Брой оценки: ${m.count}</div>`;stats.appendChild(div);overall.total+=m.total;overall.count+=m.count}});if(overall.count){const g=document.createElement('div');g.className='stat';g.innerHTML=`<div><strong>Общ среден успех</strong></div><div style="font-size:20px">${+(overall.total/overall.count).toFixed(2)}</div><div>Общо оценки: ${overall.count}</div>`;stats.appendChild(g)}}
function addSubject(){const name=el('subjectName').value.trim();const color=el('subjectColor').value||'#4caf50';if(!name) return;state.subjects.push({id:uid(),name,color});save();renderAll();el('subjectName').value=''}
function addGrade(){const subj=el('selSubject').value;const val=el('gradeValue').value.trim();const date=el('gradeDate').value||new Date().toISOString().slice(0,10);const type=el('gradeType').value;const comment=el('gradeComment').value.trim();if(!subj||!val) return;state.grades.push({id:uid(),subject:subj,value:val,date,type,comment});save();renderAll();el('gradeValue').value='';el('gradeComment').value=''}
function deleteSubject(id){state.subjects=state.subjects.filter(s=>s.id!==id);state.grades=state.grades.filter(g=>g.subject!==id);save();renderAll()}
function deleteGrade(id){state.grades=state.grades.filter(g=>g.id!==id);save();renderAll()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='gradebook_export.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function importDataFromFile(file){const reader=new FileReader();reader.onload=e=>{try{const data=JSON.parse(e.target.result);if(data.subjects && data.grades){state=data;save();renderAll()}}catch(err){alert('Невалиден файл')}};reader.readAsText(file)}
function renderAll(){renderSubjects();renderGrades();computeStats()}
document.addEventListener('click',e=>{if(e.target.id==='addSubject') addSubject(); if(e.target.id==='addGrade') addGrade(); if(e.target.id==='toggleTheme'){document.body.classList.toggle('dark')} if(e.target.id==='exportBtn') exportData(); if(e.target.classList.contains('del-sub')) deleteSubject(e.target.dataset.id); if(e.target.classList.contains('del-grade')) deleteGrade(e.target.dataset.id); if(e.target.id==='importBtn') el('importFile').click()})
el('importFile').addEventListener('change',e=>{const f=e.target.files[0]; if(f) importDataFromFile(f)})
load()
if(state.subjects.length===0 && state.grades.length===0){state.subjects=[{id:uid(),name:'Математика',color:'#4caf50'},{id:uid(),name:'Български',color:'#ff9800'}];state.grades=[{id:uid(),subject:state.subjects[0].id,value:'5.50',date:new Date().toISOString().slice(0,10),type:'Контролно',comment:''}];save()}
renderAll()
